### ISSUE TITLE
Kronecker product G covariance structure error

### ISSUE THREAD

**Issue by Dekermanjian** [cran/sommer#5]
Hello, I am trying to fit a model to replicate some SAS output that uses kronecker (direct product) covariance structures. I am trying to follow and adapt the example that is provided using the DT_cpdata to fit my model. The code that I am using is 
`model1 = mmer(data = df,
             fixed = y ~ group*time,
             random = ~vs(time:group, Gu = kronecker(us(group), us(time), make.dimnames = T)),
             rcov = ~id,
             method = "REML"
)`
The data I have has 3 groups (factors) 5 times (factors) and 6 ids (factors). I am trying to specify my R matrix as the direct product of unstructured covariance for group and unstructured covariance pattern for time. And to specify the blocks of the G matrix by the subject (the id variable).  However the code I have above returns the error "Error in tcrossprod(x, y) : requires numeric/complex matrix/vector arguments". 

I am a new user of mmer() so any help/advice will be greatly appreciated.

**Comment by gaborcsardi** [comment]
Hi, this is a read only mirror of CRAN, please see the package authors in the `DESCRIPTION` file. Thanks!
